#Travis CI

language: php

php:
 - 7.0

branches:
 - master
 - 2.0.0

before_script:
 - phpenv config-rm xdebug.ini
 - git clone --depth=50 --branch=php7 https://github.com/ClearSkyTeam/ClearSky.git
 - pecl install channel://pecl.php.net/pthreads-3.1.6
 - pecl install channel://pecl.php.net/weakref-0.3.2
 - echo | pecl install channel://pecl.php.net/yaml-2.0.0RC8
 - cd ClearSky
 - mkdir plugins
 - cd plugins
 - wget -O plugins/DevTools.phar https://github.com/PocketMine/DevTools/releases/download/v1.11.0/DevTools_v1.11.0.phar
 - cd /home/travis/build/robske110/BanWarn/
 - cp -rf Travis.php ClearSky/
 - cp -rf English/ ClearSky/plugins/
 - cd ClearSky

script:
 - php Travis.php
 
notifications:
 email: false
